[package]
name = "ouroboros"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "ouroboros"

[features]
no-entrypoint = []
no-idl = []
devnet = ["anchor-spl/devnet"]
cpi = ["no-entrypoint"]
default = []

[dependencies]
solana-program = "1.9.2"
anchor-lang = "0.19.0"
anchor-spl = "0.19.0"
thiserror = "1.0.30"